# Generated by Django 5.1.6 on 2025-03-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='duracion',
        ),
    ]
