# Generated by Django 5.1.6 on 2025-05-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cliente_direccion_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
