# Generated by Django 5.1.6 on 2025-05-24 20:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 24, 20, 13, 21, 318918, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo_realizado', models.TextField(help_text='Descripción detallada del trabajo realizado')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('repuestos_utilizados', models.TextField(blank=True, help_text='Repuestos o materiales utilizados')),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo adicional por repuestos', max_digits=10)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('tecnico_responsable', models.CharField(blank=True, max_length=100)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
            ],
            options={
                'verbose_name': 'Historial de Servicio',
                'verbose_name_plural': 'Historiales de Servicios',
            },
        ),
    ]
