# Generated by Django 5.1.6 on 2025-05-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_cita_fecha_actualizacion_cita_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='HistorialServicio',
        ),
    ]
