# Generated by Django 5.1.6 on 2025-05-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_remove_cita_fecha_creacion_alter_cita_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
