# Generated by Django 5.1.6 on 2025-05-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='informe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
